### ISSUE TITLE
Invalid Response in APIs

### ISSUE THREAD

**Issue by AkhileshNegi** [OpenNyAI/jugalbandi-api#1]
**Description**
While using API getting below as API response 
```
n_components(300) must be <= n_features(110)
```

**Additional Context**

**UUID:** "2e7b95e6-0436-11ee-bf11-8d7826ff6b15"
**URL:** "https://api.jugalbandi.ai/query-with-langchain-gpt3-5"
**Query:** "I want to learn about Bandhu housing and the different housing options"

**Comment by KaranrajM** [comment]
Hi Akhilesh, I hope the newly deployed APIs resolved this error. Please let me know if you find this error again.
